### ISSUE TITLE
logger and memoryleak detection.

### ISSUE THREAD

**Issue by JohanG2012** [reftoken/api-boilerplate#17]
Would be good with a logger to .json files for production and a memoryleak detection pakage.

Suggestions:
Bunyan
memwatch

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/745266343190104/775679587135879)

**Comment by beppek** [comment]
I found a [faster logger than bunyan](https://github.com/pinojs/pino/blob/master/docs/benchmarks.md), pino, which looks promising.

**Comment by beppek** [comment]
Memwatch doesn't seem to detect memory leaks. I need to investigate this by creating some memory leaks to see if I can find out the issue. Re-opening this issue.

**Comment by beppek** [comment]
Works now. Closing issue again
